### ISSUE TITLE
Redstone Selling bin causing Render thread/ERROR spam & bug in time display

### ISSUE THREAD

**Issue by abrossimow** [bigchadguys/SellingBin#3]
Adding item to the Selling Bin redstone variant with a Create belt causes a console spam with Render Thread Errors.
Also the countdown of the Selling Bin stops to work.

Version: 1.0.9
Fabric 0.16.7 - MC 1.20.1

```
[09:50:51] [Render thread/ERROR]: Error executing task on Client
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.util.Arrays$ArrayList.set(Arrays.java:4170) ~[?:?]
	at net.minecraft.class_2371.set(class_2371.java:54) ~[client-intermediary.jar:?]
	at bigchadguys.sellingbin.SellingBinInventory.lambda$readNbt$4(SellingBinInventory.java:242) ~[SellingBin-mc1.20.1-v1.0.9-fabric.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at bigchadguys.sellingbin.SellingBinInventory.lambda$readNbt$5(SellingBinInventory.java:240) ~[SellingBin-mc1.20.1-v1.0.9-fabric.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at bigchadguys.sellingbin.SellingBinInventory.readNbt(SellingBinInventory.java:239) ~[SellingBin-mc1.20.1-v1.0.9-fabric.jar:?]
	at bigchadguys.sellingbin.block.entity.SellingBinBlockEntity.readNbt(SellingBinBlockEntity.java:96) ~[SellingBin-mc1.20.1-v1.0.9-fabric.jar:?]
	at net.minecraft.class_634.handler$jdi001$sellingbin$onBlockEntityUpdate(class_634.java:20740) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11094(class_634.java:1265) ~[client-intermediary.jar:?]
	at net.minecraft.class_2622.method_11292(class_2622.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.class_2622.method_11054(class_2622.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.16.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.7.jar:?]
```
And on tick:
```
...
[10:15:12] [Render thread/ERROR]: Error executing task on Client
java.lang.ArrayIndexOutOfBoundsException: null
[10:15:13] [Render thread/ERROR]: Error executing task on Client
java.lang.ArrayIndexOutOfBoundsException: null
...
```

**Comment by abrossimow** [comment]
Maybe even causing crash by ticking when using create:chute on top of Redstone Selling bin.
Reproduce: Place create:chute on top of Redstone Selling Bin, throw item in chute.

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-10-29 11:06:29
Description: Ticking block entity

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at knot//net.fabricmc.fabric.impl.transfer.item.SidedInventoryStorageImpl.createWrapperList(SidedInventoryStorageImpl.java:53)
	at knot//net.fabricmc.fabric.impl.transfer.item.SidedInventoryStorageImpl.<init>(SidedInventoryStorageImpl.java:38)
	at knot//net.fabricmc.fabric.impl.transfer.item.InventoryStorageImpl.getSidedWrapper(InventoryStorageImpl.java:110)
	at knot//net.fabricmc.fabric.impl.transfer.item.InventoryStorageImpl.of(InventoryStorageImpl.java:65)
	at knot//net.fabricmc.fabric.api.transfer.v1.item.InventoryStorage.of(InventoryStorage.java:66)
	at knot//net.fabricmc.fabric.api.transfer.v1.item.ItemStorage.lambda$static$2(ItemStorage.java:114)
	at knot//net.fabricmc.fabric.impl.lookup.block.BlockApiLookupImpl.find(BlockApiLookupImpl.java:99)
	at knot//io.github.fabricators_of_create.porting_lib.transfer.TransferUtil.getItemStorage(TransferUtil.java:130)
	at knot//io.github.fabricators_of_create.porting_lib.transfer.internal.cache.ClientItemLookupCache.find(ClientItemLookupCache.java:58)
	at knot//io.github.fabricators_of_create.porting_lib.transfer.internal.cache.ClientItemLookupCache.find(ClientItemLookupCache.java:25)
	at knot//net.fabricmc.fabric.api.lookup.v1.block.BlockApiCache.find(BlockApiCache.java:55)
	at knot//io.github.fabricators_of_create.porting_lib.util.StorageProvider$CachedStorageProvider.get(StorageProvider.java:116)
	at knot//com.simibubi.create.content.logistics.chute.ChuteBlockEntity.grabCapability(ChuteBlockEntity.java:538)
	at knot//com.simibubi.create.content.logistics.chute.ChuteBlockEntity.handleDownwardOutput(ChuteBlockEntity.java:373)
	at knot//com.simibubi.create.content.logistics.chute.ChuteBlockEntity.tick(ChuteBlockEntity.java:174)
	at knot//com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15)
	at knot//net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at knot//net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at knot//net.minecraft.class_1937.method_18471(class_1937.java:470)
	at knot//net.minecraft.class_638.method_18116(class_638.java:259)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1901)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1181)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at knot//net.fabricmc.fabric.impl.transfer.item.SidedInventoryStorageImpl.createWrapperList(SidedInventoryStorageImpl.java:53)
	at knot//net.fabricmc.fabric.impl.transfer.item.SidedInventoryStorageImpl.<init>(SidedInventoryStorageImpl.java:38)
	at knot//net.fabricmc.fabric.impl.transfer.item.InventoryStorageImpl.getSidedWrapper(InventoryStorageImpl.java:110)
	at knot//net.fabricmc.fabric.impl.transfer.item.InventoryStorageImpl.of(InventoryStorageImpl.java:65)
	at knot//net.fabricmc.fabric.api.transfer.v1.item.InventoryStorage.of(InventoryStorage.java:66)
	at knot//net.fabricmc.fabric.api.transfer.v1.item.ItemStorage.lambda$static$2(ItemStorage.java:114)
	at knot//net.fabricmc.fabric.impl.lookup.block.BlockApiLookupImpl.find(BlockApiLookupImpl.java:99)
	at knot//io.github.fabricators_of_create.porting_lib.transfer.TransferUtil.getItemStorage(TransferUtil.java:130)
	at knot//io.github.fabricators_of_create.porting_lib.transfer.internal.cache.ClientItemLookupCache.find(ClientItemLookupCache.java:58)
	at knot//io.github.fabricators_of_create.porting_lib.transfer.internal.cache.ClientItemLookupCache.find(ClientItemLookupCache.java:25)
	at knot//net.fabricmc.fabric.api.lookup.v1.block.BlockApiCache.find(BlockApiCache.java:55)
	at knot//io.github.fabricators_of_create.porting_lib.util.StorageProvider$CachedStorageProvider.get(StorageProvider.java:116)
	at knot//com.simibubi.create.content.logistics.chute.ChuteBlockEntity.grabCapability(ChuteBlockEntity.java:538)
	at knot//com.simibubi.create.content.logistics.chute.ChuteBlockEntity.handleDownwardOutput(ChuteBlockEntity.java:373)
	at knot//com.simibubi.create.content.logistics.chute.ChuteBlockEntity.tick(ChuteBlockEntity.java:174)
	at knot//com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15)
	at knot//net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at knot//net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at knot//net.minecraft.class_1937.method_18471(class_1937.java:470)
	at knot//net.minecraft.class_638.method_18116(class_638.java:259)

-- Block entity being ticked --
Details:
	Name: create:chute // com.simibubi.create.content.logistics.chute.ChuteBlockEntity
	Block: Block{create:chute}[facing=down,shape=normal,waterlogged=false]
	Block location: World: (-90,75,-1517), Section: (at 6,11,3 in -6,4,-95; chunk contains blocks -96,-64,-1520 to -81,319,-1505), Region: (-1,-3; contains chunks -32,-96 to -1,-65, blocks -512,-64,-1536 to -1,319,-1025)
	Block: Block{create:chute}[facing=down,shape=normal,waterlogged=false]
	Block location: World: (-90,75,-1517), Section: (at 6,11,3 in -6,4,-95; chunk contains blocks -96,-64,-1520 to -81,319,-1505), Region: (-1,-3; contains chunks -32,-96 to -1,-65, blocks -512,-64,-1536 to -1,319,-1025)
Stacktrace:
	at knot//net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at knot//net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at knot//net.minecraft.class_1937.method_18471(class_1937.java:470)
	at knot//net.minecraft.class_638.method_18116(class_638.java:259)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1901)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1181)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

**Comment by Anettei** [comment]
I have the same exact problem. I have also noticed that when you place an emerald in the Redstone Selling Bin, the timer visually stops counting down but it doesnt actually stop counting down. you just gotta take the emerald out to see the timer count down. and this only occurs with the Redstone Selling Bin.
